### ISSUE TITLE
Problema com variáveis locais 

### ISSUE THREAD

**Issue by igorfratel** [batmacumba/libcc#2]
Estamos usando ponteiros void para que as estruturas sejam genéricas.
Isso funciona quando as variáveis guardadas nas estruturas continuam existindo no programa, mas quando usamos variáveis locais de funções que são executadas e encerradas, temos uma inconsistência.

## Exemplo que funciona:
```
int main() {
        Bag *bag = Bag_new();
        int *pointer;
        int tmp1 = 1;
        pointer = &tmp1;
        Bag_add(bag, pointer);
        int **bag_items = (int**) Bag_iterator(bag);
        for (int i = 0; i < Bag_size(bag); i++) {
            printf("item %d = %d\n", i, *bag_items[i]);
        }
}
```

## Exemplo que não funciona:
```
void f1(Bag *bag) {
        int *pointer;
        int tmp1 = 1;
        pointer = &tmp1;
        Bag_add(bag, pointer);
}

int main() {
        Bag *bag = Bag_new();
        f1(bag);
        int **bag_items = (int**) Bag_iterator(bag);
        for (int i = 0; i < Bag_size(bag); i++) {
            printf("item %d = %d\n", i, *bag_items[i]);
        }
}
```
Pois a variável tmp1 some depois que a função f1 é encerrada.

## Exemplo que funciona mas causa memory leak:
```
void f1(Bag *bag) {
        int *pointer = malloc(sizeof(int));
        *pointer = 1;
        Bag_add(bag, pointer);
}

int main() {
        Bag *bag = Bag_new();
        f1(bag);
        int **bag_items = (int**) Bag_iterator(bag);
        for (int i = 0; i < Bag_size(bag); i++) {
            printf("item %d = %d\n", i, *bag_items[i]);
        }
}
```
Como a variável está alocada no heap, não tem problema dela desaparecer. Mas agora temos um memory leak pois não demos free nela (acho imprático exigir que o usuário dê free em todas as variáveis que ele armazenar nas nossas estruturas).

**Comment by batmacumba** [comment]
Boa Igor! Me parece que o problema é que as EDs não estão copiando os dados, só guardando os endereços pros dados, certo?
Existe alguma forma da gente copiar esses dados e manter o "design" genérico das implementações?

**Comment by batmacumba** [comment]
Concordo em deixar aberto a issue até a gente modificar tudo. Aos poucos vamos consolidando conceitos pra lib em geral, mas uma coisa que eu acho desejável é robustez. Me parece que copiar os itens é o comportamento esperado de uma ED não?

**Comment by batmacumba** [comment]
Resolvi o problema e implementei no bag. Agora no momento da inserção de um novo item, alocamos o espaço no heap para o item e copiamos o conteúdo para "dentro da ED". Assim não é possível alterar o conteúdo da ED sem uma função explícita para isso. O único efeito colateral é que é necessário passar mais um argumento à função Bag_add. Ela ficou com a seguinte assinatura:
```
Bag_add(Bag *b, void *data, size_t dataSize)
```
Por consequência, Stack_push, Queue_enqueue e Vector_pushBack provavelmente também terão as suas assinaturas modificadas. Eu coloquei um macro em Bag para amenizar o problema:
```
#define Bag_add(b, data) Bag_add(b, data, sizeof(data))
```
É gambi? A outra possibilidade era restringir o tamanho do item na inicialização da ED, assim:
```
Bag *b = Bag_new(sizeof(data_type))
```
Só que isso tem um efeito bem pior que é o de não permitir strings com tamanhos maiores do que o definido na inicialização.
